### PR TITLE
chore(deps): use node 16

### PR DESCRIPTION
**Pull request by smlgbl**
### Checklist

- [ ] This PR includes a documentation change
- [x] This PR does not need a documentation change
---
- [ ] This PR includes test changes
- [x] This PR's changes are already tested
---
- [ ] This change is not user-facing
- [ ] This change is a patch change
- [x] This change is a minor change
- [ ] This change is a major (breaking) change

### CODE REVIEW

**Comment by smlgbl** [comment]
I'm having problems with the minify step when using together with source-map.
Anybody more experienced with typescript who can help?

**Review by divyansh42 — APPROVED** [review]

**Comment by divyansh42** [comment]
@smlgbl can you please rebase your PR?

**Comment by divyansh42** [comment]
@smlgbl Could you please check if you have build the bundles correctly? 
If not, please run `npm run bundle`

**Comment by smlgbl** [comment]
> @smlgbl Could you please check if you have build the bundles correctly? If not, please run `npm run bundle`

Like I wrote before, everytime I do that, it gives me the following, and it's not minified:
```ncc: Version 0.34.0
ncc: Compiling file index.js into CJS
ncc: Using typescript@4.9.4 (local user-provided)
An error occurred while minifying. The result will not be minified.
 40kB  dist/sourcemap-register.js
268kB  dist/index.js
315kB  dist/index.js.map
315kB  dist/index.js.map
623kB  [1138ms] - ncc 0.34.0
```
Maybe I can give you write access, and you run it?

**Review by divyansh42 — APPROVED** [review]

**Comment by divyansh42** [comment]
Thanks for your PR @smlgbl

**Comment by divyansh42** [comment]
@smlgbl could you please sign your commits?

**Comment by smlgbl** [comment]
> @smlgbl could you please sign your commits? Also feel free to squash the commits into one commit.

Sorry, hadn't signed anything before, hence it took a while.

**Comment by divyansh42** [comment]
> > @smlgbl could you please sign your commits? Also feel free to squash the commits into one commit.
> 
> Sorry, hadn't signed anything before, hence it took a while.

No worries :hugs:

**Review by divyansh42 — APPROVED** [review]
cc @jduimovich

**Pull request merged**
