### PR TITLE
chore(deps): use node 20

### PR DESCRIPTION
**Pull request by sepulvedablanco**
### Description

Update the action to use node 20

### Related Issue(s)

https://github.com/redhat-actions/oc-login/issues/35

### Checklist

- [ ] This PR includes a documentation change
- [X] This PR does not need a documentation change
---
- [ ] This PR includes test changes
- [X] This PR's changes are already tested
---
- [ ] This change is not user-facing
- [ ] This change is a patch change
- [X] This change is a minor change
- [ ] This change is a major (breaking) change

### Changes made

Upgrade dependencies

### CODE REVIEW

**Review by smlgbl — APPROVED** [review]

**Comment by gastaldi** [comment]
Can someone merge this and release it? The NodeJS 16 warnings are pretty annoying

**Comment by divyansh42** [comment]
@sepulvedablanco thanks for your PR! 👍 
I will look at it very soon. Apologies for the delays.

**Review by divyansh42 — CHANGES_REQUESTED** [review]
Changes looks good to me.
Could you please rebase your PR?
Also could you please run these two commands so that generated input outputs and bundles are updated?
```
npx action-io-generator -w -o ./src/generated/inputs-outputs.ts
npm run bundle
```

**Comment by sepulvedablanco** [comment]
done @divyansh42

**Review by divyansh42 — APPROVED** [review]

**Comment by divyansh42** [comment]
@sepulvedablanco could you please sign your commits as well?

**Comment by sepulvedablanco** [comment]
done @divyansh42

**Comment by sepulvedablanco** [comment]
@divyansh42 friendly reminder

**Review by divyansh42 — APPROVED** [review]

**Pull request merged**
